name: Criar comentario com issue

on:
  issues:
    types: [opened]

jobs:
  criar_comentario:
    runs-on: ubuntu-latest
    steps:
      - name: mostrar github context
        run: |
          echo "${GITHUB_CONTEXT}" | jq .
          echo "${{toJson(github.event)}}" | jq .
        shell: bash 