name: comentario com a API do GitHub
on:
  issue_comment:
    types: [created]
jobs:
  comentario:
    runs-on: ubuntu-latest
    steps:
      - name: Responder a um comentário de issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentBody = context.payload.comment.body;
            if (commentBody.includes('Olá')) {
              const issueNumber = context.payload.issue.number;
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'Olá! Obrigado pelo seu comentário.'
              });
            }
            else if (commentBody.includes('Adeus')) {
              const issueNumber = context.payload.issue.number;
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: 'Adeus! Foi bom falar com você.'
              });
            }